# Descriptive Statistics Using Numpy

In [4]:
import numpy as np

#### Descriptive Statistics of List Using Numpy:

In [7]:
lst = [12,15,17,90,31,42,54,32,12,12]

In [8]:
# Finding Mean

np.mean(lst)

31.7

In [9]:
# Finding Median

np.median(lst)

24.0

In [11]:
# Finding Standata Deviation

np.std(lst)

23.795167576632025

In [12]:
# Finding Variance
np.var(lst)

566.21

#### Descriptive Statistics of 1-D Array Using Numpy:

In [14]:
array_1d = np.random.randint(0,50,25) 

In [15]:
array_1d

array([ 0, 30,  0, 47, 49, 21, 42,  8,  3, 19, 17, 44, 28,  9, 11, 47,  5,
       15, 14, 43, 30, 29, 36, 40, 31])

In [16]:
# Mean of 1-D Array
np.mean(array_1d)

24.72

In [17]:
# Mean of 1-D Array
array_1d.mean()

24.72

In [18]:
# Median of 1-D Array
np.median(array_1d)

28.0

In [20]:
# Variance of 1-D Array
np.var(array_1d)

247.4016

In [21]:
# Variance of 1-D Array
array_1d.var()

247.4016

In [22]:
# Standard Deviation of 1-D Array
np.std(array_1d)

15.72900505435738

In [23]:
# Standard Deviation of 1-D Array
array_1d.std()

15.72900505435738

#### Descriptive Statistics of 2-D Array Using Numpy:

In [24]:
array_2d = array_1d.reshape(5,5)

In [25]:
array_2d

array([[ 0, 30,  0, 47, 49],
       [21, 42,  8,  3, 19],
       [17, 44, 28,  9, 11],
       [47,  5, 15, 14, 43],
       [30, 29, 36, 40, 31]])

In [26]:
# Mean of All Elements in 2-D Array
np.mean(array_2d)

24.72

In [27]:
# Mean of All Elements in 2-D Array
array_2d.mean()

24.72

In [28]:
# Median of All Elements in 2-D Array
np.median(array_2d)

28.0

In [29]:
# Variance of All Elements in 2-D Array
np.var(array_2d)

247.4016

In [30]:
# Variance of All Elements in 2-D Array
array_2d.var()

247.4016

In [31]:
# Standarad Deviation of All Elements in 2-D Array
np.std(array_2d)

15.72900505435738

In [32]:
# Standarad Deviation of All Elements in 2-D Array
array_2d.std()

15.72900505435738

In [33]:
array_2d

array([[ 0, 30,  0, 47, 49],
       [21, 42,  8,  3, 19],
       [17, 44, 28,  9, 11],
       [47,  5, 15, 14, 43],
       [30, 29, 36, 40, 31]])

In [ ]:
# Mean, Median, Standard Deviation and Variance Across Rows od 2-D Array

In [34]:
np.mean(array_2d, axis = 0) # Axis= 0 Meaning Mean Across The Rows

array([23. , 30. , 17.4, 22.6, 30.6])

In [36]:
array_2d.mean(axis= 0)

array([23. , 30. , 17.4, 22.6, 30.6])

In [35]:
np.mean(array_2d, axis = 1) # Axis= 1 Meanind Mean Across The Columns

array([25.2, 18.6, 21.8, 24.8, 33.2])

In [37]:
array_2d.mean(axis= 1)

array([25.2, 18.6, 21.8, 24.8, 33.2])

In [38]:
np.median(array_2d, axis = 0) # Axis= 0 Meaning Median Across The Rows

array([21., 30., 15., 14., 31.])

In [39]:
np.median(array_2d, axis = 1) # Axis= 0 Meaning Median Across The Columns

array([30., 19., 17., 15., 31.])

In [40]:
np.var(array_2d, axis = 0) # Axis= 0 Meaning Variance Across The Rows

array([238.8 , 193.2 , 171.04, 308.24, 202.24])

In [41]:
array_2d.var(axis= 0)

array([238.8 , 193.2 , 171.04, 308.24, 202.24])

In [42]:
np.var(array_2d, axis = 1) # Axis= 1 Meaning Variance Across The Columns

array([466.96, 181.84, 166.96, 285.76,  17.36])

In [43]:
array_2d.var(axis= 1)

array([466.96, 181.84, 166.96, 285.76,  17.36])

In [44]:
np.std(array_2d, axis = 0) # Axis= 0 Meaning Standard Deviation Across The Rows

array([15.45315502, 13.89964028, 13.07822618, 17.55676508, 14.22111107])

In [45]:
array_2d.std(axis= 0 )

array([15.45315502, 13.89964028, 13.07822618, 17.55676508, 14.22111107])

In [46]:
np.std(array_2d, axis = 1) # Axis= 1 Meaning Standard Deviation Across The Columns

array([21.60925728, 13.48480626, 12.92130024, 16.90443729,  4.16653333])

In [48]:
array_2d.std(axis= 1)

array([21.60925728, 13.48480626, 12.92130024, 16.90443729,  4.16653333])